### ISSUE TITLE
DM対応について

### ISSUE THREAD

**Issue by Sayamame-beans** [kobi32768/quotebot#13]
現在、DMからQuoteBotに対してメッセージを送信した場合もメッセージ受信イベントが呼ばれるようになっています。
しかしながら、実際にはDMから送信された場合は想定されておらず、幾つかの処理が対応していません。
対応するようにしますか?

**Comment by kobi32768** [comment]
> 幾つかの処理が対応していません。

具体的にはどういったものですか

**Comment by Sayamame-beans** [comment]
例えば、
- DM用のURLに非対応
- TextChannelではないため、isSameChannel()で例外(isNSFW等も?)

があります。
まだしっかりと確認出来ていませんが…他にも問題点がある可能性はあると考えています。

**Comment by kobi32768** [comment]
なるほど
悩ましいところではあるけど あまりにコストが高いようであれば非対応でいいかもしれない

**Comment by Sayamame-beans** [comment]
加えて、isSameGuild()でも例外が発生しそうですね…(DM側にguildが無いため)
その辺りに適当な修正を入れれば対応出来そう…?

逆に、DM側から引用可能にする必要は無い気がしてきました。直接書けば良いはずなので。
