### ISSUE TITLE
TextChannel以外のチャンネルに対応(スレッド機能等)

### ISSUE THREAD

**Issue by Sayamame-beans** [kobi32768/quotebot#14]
# 内容
現状のQuote BotではDiscordのスレッド機能に対応していません。

# 考えられる対処法
現在使用されているバージョンの[JDA](https://github.com/DV8FromTheWorld/JDA)がスレッド機能に対応していない可能性が高く、バージョンを上げる必要があると考えられます。
安定しているかは不明です。

そのため、#11 の対処を行うのであれば、JDA更新作業を同時に行うのが望ましいと考えます。
スレッド機能への対応はその後の方が良いと考えられます。

**Comment by Sayamame-beans** [comment]
#15 よりJDAを更新したため、スレッド機能への対応が可能となりました。
また、VCに追加されたチャット用チャンネルがVoiceChannelに含まれることに気が付きましたため、同時に対応を試みます。

**Comment by Sayamame-beans** [comment]
スレッドに対応する場合、 #8 のように表記方法を改める必要がありそうですね…
どの様な表記にしましょうか?
@kobi32768 @anatawa12

**Comment by kobi32768** [comment]
安直に行くと `from: カテゴリ名 / Ch名 / スレッド名 (サーバー名)` になりそうなんですが 情報量が増えすぎかなという感じもある......

**Comment by anatawa12** [comment]
普通に`category / channel / thread`だと思います。長いけど欲しい情報は全てだと思うので

**Comment by Sayamame-beans** [comment]
サーバー名とカテゴリ名には` ()/`が全て使えるために、分けて置いたような記憶があります…(うろ覚え)
ではスレッドはというと` ()`が使用可能なようです。
従って、私も`from: category / channel / thread (server)`で良いのかな、という感じですね。
その形式にしたいと思います。

**Comment by Sayamame-beans** [comment]
アーカイブされたスレッドからのメッセージを引用出来ない問題についてですが、[Discord Developer Portal — Documentation — Threads](https://discord.com/developers/docs/topics/threads#active-archived-threads)を見ると、`archived threads are not synced up-front via the gateway.`とあり、取得出来るように作られていない可能性があります。
また、[この箇所](https://discord.com/developers/docs/topics/threads#public-private-threads)には`The created thread and the message it was started from will share the same id.`とあり、そちらからの迂回も検討しましたが、MessageById系のメソッドは対象のメッセージがあるChannelからしか呼び出すことが出来ないため断念しました。

しかしながら、[Javadoc (JDA 5.0.0-alpha.17_67566a8 API)](https://ci.dv8tion.net/job/JDA5/javadoc/index.html)内にはそのような記述が見受けられなかった様に思います(要確認)ので、[JDA](https://github.com/DV8FromTheWorld/JDA)としてはどの様な挙動が想定されているのか等を確認する必要があるかもしれません。

**Comment by anatawa12** [comment]
一旦アーカイブスレッドの対応を後回し(別issueを投稿)して、マージするのもありだと思います

**Comment by Sayamame-beans** [comment]
そうですね…
一応、PrivateThreadの扱いをどうするかも考えていたのですが、Boost済みのサーバーでないと実験出来ないというのもあるので、こちらも一旦保留にしておきますか?

**Comment by anatawa12** [comment]
ですね。一旦保留でいいと思います
