### ISSUE TITLE
token.txtがクラスパス上にないといけない。

### ISSUE THREAD

**Issue by anatawa12** [kobi32768/quotebot#16]
この実装では、`token.txt`がクラスパス上にないといけません。

https://github.com/kobi32768/quotebot/blob/0e2483a2a2868e878c313013c3d19e830a729b16/src/main/kotlin/io/github/kobi32768/quotebot/Main.kt#L24-L27

しかし、クラスパスは `quotebot[.bat]` によって自動設定されるため、ユーザーは設定しません。

token.txtをCWD等ユーザーが編集可能なディレクトリから読まなければいけません。

**Comment by anatawa12** [comment]
token.txt on CWDより環境変数のほうが適切だと思ったため一旦closeしました。どちらがいいですかね

**Comment by Sayamame-beans** [comment]
どうでしょう…
環境変数だと、複数のBOTを同時に動作させることが困難になるような気もします。

**Comment by anatawa12** [comment]
起動スクリプト等で指定する前提なので、動作させるのが困難になることはないと考えてます。少なくともシステムの環境変数や.bashrc等に書く前提ではないです。

明確な理由があるわけではないんですが、環境変数のほうが一般的だという認識があるんですよね。

あとはdocker対応のときに環境変数のほうが都合が良かったりします

**Comment by anatawa12** [comment]
もし開発時のことを考えてるのでしたら.envなどはどうでしょうか。

**Comment by Sayamame-beans** [comment]
なるほど。

> 環境変数のほうが一般的だという認識

これが実際にどうなのかは判断出来かねますが、しかしtxtファイルから読み出すというのも確かに違和感があります。
従って、そちら(環境変数指定式。`.env`はどちらでも。)の方が良いのかもしれません。
