### ISSUE TITLE
downgrade to java 8

### ISSUE THREAD

**Issue by anatawa12** [kobi32768/quotebot#26]
Currently, this project uses JDK 14, which is after EOL in many distributions of OpenJDK.

https://github.com/kobi32768/quotebot/blob/f8058b7b9b194fe2396655b0cf3fff9d54923129/.idea/misc.xml#L7

However, in `build.gradle.kts`, target version is specified to Java 1.8.

https://github.com/kobi32768/quotebot/blob/f8058b7b9b194fe2396655b0cf3fff9d54923129/build.gradle.kts#L28

Java 8 is still supported on many distributions. (e.g. Zulu, Temurin, Semeru)
So I suggest to use Java 8 to build this project.

**Comment by anatawa12** [comment]
OpenJDK 8 will be supported until Nov 2026 (by RedHat: see [doc][doc-redhat]).

[doc-redhat]: https://access.redhat.com/articles/1299013

**Comment by Sayamame-beans** [comment]
Probably good suggestion.
