### ISSUE TITLE
use <> for disable quote instead of \

### ISSUE THREAD

**Issue by anatawa12** [kobi32768/quotebot#38]
Current implementation ignores \\-started URLs. In discord, <>-qouted URLs will not have thumbnail. So, I think it's better to use <>-quoted for disable quotebot.

**Comment by Sayamame-beans** [comment]
Good suggestion.
The `\` style escape is easy to type, but as you say, `<>` style escape is the same way as the discord URL escape style.

**Comment by Sayamame-beans** [comment]
Using this for a while, I feel it's inconvenient because `<>` style escape does disable post source display.
How do you think?

**Comment by anatawa12** [comment]
当初リンクがそうならなかったから<>が適切だったけど今は違うか...でも\がいいとも思えない

**Comment by Sayamame-beans** [comment]
うーむ…
`-q`とかで黙らせる…?
